version: '3'
services:
  backend:
    build:
      context: ./t2-talentprogram-project-b/backend
    ports:
      - '4000:4000'
    container_name: backend
    volumes:
      - ./t2-talentprogram-project-b/backend
      - /t2-talentprogram-project-b/backend/node_modules
  frontend:
    build:
      context: ./t2-talentprogram-project-b/frontend
    ports:
      - '3080:3080'
    container_name: frontend
    stdin_open: true
    volumes:
      - ./t2-talentprogram-project-b/frontend
      - /t2-talentprogram-project-b/frontend/node_modules
